import type { DocumentModel } from './model-card';

export const mockModels: DocumentModel[] = [
    {
        id: '1',
        name: 'Contrato de honorários',
        description: 'Modelo padrão para contratação de serviços advocatícios.',
        category: 'Contrato',
        area: 'Genérico',
        version: 'v4',
        usage: 68,
        status: 'active',
        updatedAtLabel: 'Atualizado há 2 dias',
    },
    {
        id: '2',
        name: 'Petição inicial cível',
        description: 'Estrutura base com qualificação, fatos, fundamentos e pedidos.',
        category: 'Petição',
        area: 'Cível',
        version: 'v7',
        usage: 41,
        status: 'active',
        updatedAtLabel: 'Atualizado há 5 dias',
    },
    {
        id: '3',
        name: 'Procuração ad judicia',
        description: 'Procuração com poderes gerais e campos de qualificação.',
        category: 'Procuração',
        area: 'Genérico',
        version: 'v3',
        usage: 52,
        status: 'active',
        updatedAtLabel: 'Atualizado há 8 dias',
    },
    {
        id: '4',
        name: 'Ficha de atendimento',
        description: 'Versão destinada ao cliente com relato e próximos passos.',
        category: 'Ficha',
        area: 'Genérico',
        version: 'v2',
        usage: 23,
        status: 'active',
        updatedAtLabel: 'Atualizado há 10 dias',
    },
    {
        id: '5',
        name: 'Contestação trabalhista',
        description: 'Modelo em revisão para defesas em reclamações trabalhistas.',
        category: 'Petição',
        area: 'Trabalhista',
        version: 'v1',
        usage: 0,
        status: 'draft',
        updatedAtLabel: 'Atualizado hoje',
    },
    {
        id: '6',
        name: 'Acordo extrajudicial',
        description: 'Estrutura antiga para formalização de acordo entre partes.',
        category: 'Contrato',
        area: 'Família',
        version: 'v5',
        usage: 19,
        status: 'inactive',
        updatedAtLabel: 'Atualizado há 3 meses',
    },
];
